server:
  port: 8760
  
spring:
  cloud:
    config:
      server:
        bootstrap: true
        git: 
          #uri: E:\\MyWork\\2018\\Microservice\\coud_config
          uri: https://github.com/SARFUNClub/msdemo-cloud-config.git
          clone-on-start: true
          

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
