server:
  port: ${gateway.server.port:8765}
  
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${gateway.config.url.eureka:http://localhost:8761/eureka/}
    registerWithEureka: false


